#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iptraf-ng
Version  : 1.1.4
Release  : 2
URL      : https://github.com/iptraf-ng/iptraf-ng/archive/v1.1.4/iptraf-ng-1.1.4.tar.gz
Source0  : https://github.com/iptraf-ng/iptraf-ng/archive/v1.1.4/iptraf-ng-1.1.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: iptraf-ng-bin = %{version}-%{release}
Requires: iptraf-ng-license = %{version}-%{release}
Requires: iptraf-ng-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)
Patch1: 0001-BUGFIX-fix-Floating-point-exception-in-tcplog_flowra.patch
Patch2: 0002-Makefile-add-Werror-format-security.patch
Patch3: 0003-bugfix-positionptr-properly-allocate-newly-created-i.patch
Patch4: 0004-build-use-wide-version-of-lpanel-when-needed.patch

%description
==========================================================================
--------------------------------------------------------------------------
See the RELEASE-NOTES for important update information.
See the INSTALL file for installation instructions.
--------------------------------------------------------------------------

%package bin
Summary: bin components for the iptraf-ng package.
Group: Binaries
Requires: iptraf-ng-license = %{version}-%{release}

%description bin
bin components for the iptraf-ng package.


%package license
Summary: license components for the iptraf-ng package.
Group: Default

%description license
license components for the iptraf-ng package.


%package man
Summary: man components for the iptraf-ng package.
Group: Default

%description man
man components for the iptraf-ng package.


%prep
%setup -q -n iptraf-ng-1.1.4
cd %{_builddir}/iptraf-ng-1.1.4
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587411961
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  prefix=/usr sbindir_relative=bin


%install
export SOURCE_DATE_EPOCH=1587411961
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iptraf-ng
cp %{_builddir}/iptraf-ng-1.1.4/LICENSE %{buildroot}/usr/share/package-licenses/iptraf-ng/cad7b705cfaf125ec02188d8b8a12f1f038c4dd8
%make_install prefix=/usr sbindir_relative=bin
## install_append content
ln -s iptraf-ng %{buildroot}/usr/bin/iptraf
ln -s rvnamed-ng %{buildroot}/usr/bin/rvnamed
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iptraf
/usr/bin/iptraf-ng
/usr/bin/rvnamed
/usr/bin/rvnamed-ng

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iptraf-ng/cad7b705cfaf125ec02188d8b8a12f1f038c4dd8

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iptraf-ng.8
/usr/share/man/man8/rvnamed-ng.8
