#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: 5424026
#
Name     : iptraf-ng
Version  : 1.2.2
Release  : 6
URL      : https://github.com/iptraf-ng/iptraf-ng/archive/v1.2.2/iptraf-ng-1.2.2.tar.gz
Source0  : https://github.com/iptraf-ng/iptraf-ng/archive/v1.2.2/iptraf-ng-1.2.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: iptraf-ng-bin = %{version}-%{release}
Requires: iptraf-ng-license = %{version}-%{release}
Requires: iptraf-ng-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
==========================================================================
--------------------------------------------------------------------------
See the CHANGES file for the history of changes.
See the INSTALL file for installation instructions.
--------------------------------------------------------------------------

%package bin
Summary: bin components for the iptraf-ng package.
Group: Binaries
Requires: iptraf-ng-license = %{version}-%{release}

%description bin
bin components for the iptraf-ng package.


%package license
Summary: license components for the iptraf-ng package.
Group: Default

%description license
license components for the iptraf-ng package.


%package man
Summary: man components for the iptraf-ng package.
Group: Default

%description man
man components for the iptraf-ng package.


%prep
%setup -q -n iptraf-ng-1.2.2
cd %{_builddir}/iptraf-ng-1.2.2
pushd ..
cp -a iptraf-ng-1.2.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732201301
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  prefix=/usr sbindir_relative=bin

pushd ../buildavx2
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
make  %{?_smp_mflags}  prefix=/usr sbindir_relative=bin
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1732201301
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iptraf-ng
cp %{_builddir}/iptraf-ng-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/iptraf-ng/cad7b705cfaf125ec02188d8b8a12f1f038c4dd8 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 prefix=/usr sbindir_relative=bin
popd
GOAMD64=v2
%make_install prefix=/usr sbindir_relative=bin
## install_append content
ln -s iptraf-ng %{buildroot}/usr/bin/iptraf
ln -s iptraf-ng %{buildroot}/usr/bin/rvnamed
ln -s iptraf-ng %{buildroot}/usr/bin/rvnamed-ng
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/iptraf-ng
/usr/bin/iptraf
/usr/bin/iptraf-ng
/usr/bin/rvnamed
/usr/bin/rvnamed-ng

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iptraf-ng/cad7b705cfaf125ec02188d8b8a12f1f038c4dd8

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iptraf-ng.8
