#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iptraf-ng
Version  : 1.2.1
Release  : 4
URL      : https://github.com/iptraf-ng/iptraf-ng/archive/v1.2.1/iptraf-ng-1.2.1.tar.gz
Source0  : https://github.com/iptraf-ng/iptraf-ng/archive/v1.2.1/iptraf-ng-1.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: iptraf-ng-bin = %{version}-%{release}
Requires: iptraf-ng-license = %{version}-%{release}
Requires: iptraf-ng-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)

%description
==========================================================================
--------------------------------------------------------------------------
See the CHANGES file for the history of changes.
See the INSTALL file for installation instructions.
--------------------------------------------------------------------------

%package bin
Summary: bin components for the iptraf-ng package.
Group: Binaries
Requires: iptraf-ng-license = %{version}-%{release}

%description bin
bin components for the iptraf-ng package.


%package license
Summary: license components for the iptraf-ng package.
Group: Default

%description license
license components for the iptraf-ng package.


%package man
Summary: man components for the iptraf-ng package.
Group: Default

%description man
man components for the iptraf-ng package.


%prep
%setup -q -n iptraf-ng-1.2.1
cd %{_builddir}/iptraf-ng-1.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595345156
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  prefix=/usr sbindir_relative=bin


%install
export SOURCE_DATE_EPOCH=1595345156
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iptraf-ng
cp %{_builddir}/iptraf-ng-1.2.1/LICENSE %{buildroot}/usr/share/package-licenses/iptraf-ng/cad7b705cfaf125ec02188d8b8a12f1f038c4dd8
%make_install prefix=/usr sbindir_relative=bin
## install_append content
ln -s iptraf-ng %{buildroot}/usr/bin/iptraf
ln -s iptraf-ng %{buildroot}/usr/bin/rvnamed
ln -s iptraf-ng %{buildroot}/usr/bin/rvnamed-ng
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iptraf
/usr/bin/iptraf-ng
/usr/bin/rvnamed
/usr/bin/rvnamed-ng

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iptraf-ng/cad7b705cfaf125ec02188d8b8a12f1f038c4dd8

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iptraf-ng.8
